// Netscape cookies.txt serializer for chrome.cookies.Cookie[] inputs.
// Pure function — never logs cookie values and never reads chrome storage.
(function (root) {
  const NETSCAPE_HEADER =
    "# Netscape HTTP Cookie File\n" +
    "# https://curl.se/docs/http-cookies.html\n" +
    "# This file was generated by the Scribe Chrome extension. Do not edit.\n\n";

  function serializeCookiesToNetscape(cookies) {
    if (!Array.isArray(cookies) || cookies.length === 0) {
      return "";
    }
    const lines = [];
    for (const cookie of cookies) {
      const line = formatCookieLine(cookie);
      if (line) {
        lines.push(line);
      }
    }
    if (lines.length === 0) {
      return "";
    }
    return NETSCAPE_HEADER + lines.join("\n") + "\n";
  }

  function formatCookieLine(cookie) {
    if (!cookie || typeof cookie.name !== "string" || typeof cookie.value !== "string") {
      return null;
    }
    if (containsTabOrNewline(cookie.name) || containsTabOrNewline(cookie.value)) {
      return null;
    }
    const rawDomain = String(cookie.domain || "").trim();
    if (!rawDomain) {
      return null;
    }
    const hostOnly = Boolean(cookie.hostOnly);
    let domain;
    if (hostOnly) {
      domain = rawDomain.startsWith(".") ? rawDomain.slice(1) : rawDomain;
    } else {
      domain = rawDomain.startsWith(".") ? rawDomain : `.${rawDomain}`;
    }
    const includeSubdomains = hostOnly ? "FALSE" : "TRUE";
    const path = cookie.path && typeof cookie.path === "string" ? cookie.path : "/";
    const secure = cookie.secure ? "TRUE" : "FALSE";
    const expiration = cookie.session
      ? 0
      : Math.max(0, Math.floor(Number(cookie.expirationDate) || 0));
    const prefix = cookie.httpOnly ? "#HttpOnly_" : "";
    return [
      `${prefix}${domain}`,
      includeSubdomains,
      path,
      secure,
      String(expiration),
      cookie.name,
      cookie.value,
    ].join("\t");
  }

  function containsTabOrNewline(value) {
    return /[\t\r\n]/.test(value);
  }

  root.scribeCookies = { serializeCookiesToNetscape };

  if (typeof module !== "undefined" && module.exports) {
    module.exports = { serializeCookiesToNetscape };
  }
})(typeof globalThis !== "undefined" ? globalThis : this);
