#!/bin/bash
# Auto-generated by maestro pipeline — verification commands for this task
# Run this script to verify all requirements are met.
set -e

echo '=== Project Test Suite ==='
python -m pytest

echo '=== Requirement Verification ==='
echo 'Requirement 1: Resolve the app version dynamically from installed package metadata (e.g. `impor...'
echo 'WARN: Run tests in .codex-work/pr19/test_migrations.py'

echo 'Requirement 2: `/healthz` `.version` returns that value.'
python -m pytest

echo 'Requirement 3: Bumping `pyproject.toml` version (and rebuilding) changes `/healthz .version` wi...'
echo 'WARN: Run tests in tests/test_source_links.py'

echo 'Requirement 4: A unit test asserts `/healthz .version == importlib.metadata.version("scribe")`.'
echo 'WARN: Run tests in .codex-work/pr19/test_migrations.py'

echo 'All verifications passed.'
