#!/bin/bash
# Auto-generated by maestro pipeline — verification commands for this task
# Run this script to verify all requirements are met.
set -e

echo '=== Project Test Suite ==='
python -m pytest

echo '=== Requirement Verification ==='
echo 'Requirement 1: Extend `POST /jobs` to accept optional `{ summarize?: bool, notify?: bool, summa...'
python -m pytest

echo 'Requirement 2: Persist/honor them in the job pipeline (summarize toggle gates the codex summary...'
echo 'WARN: Run tests in .codex-work/pr19/test_migrations.py'

echo 'Requirement 3: Re-enable the three opt rows in `CaptureSheet.jsx` and wire them into the `submi...'
echo 'WARN: Run tests in web/spa/tests/CommandPalette.test.ts'

echo 'Requirement 4: `POST /jobs` accepts and honors the three optional fields; omitting them preserv...'
python -m pytest

echo 'Requirement 5: `submitJob(auth, url, opts)` forwards them; CaptureSheet toggles drive `opts`.'
python -m pytest

echo 'Requirement 6: A real submit with `summarize:false` skips the summary step (verified end-to-end...'
echo 'WARN: Run tests in tests/test_summary_circuit_breaker.py'

echo 'Requirement 7: `uv run pytest -q` covers the new request shape; SPA `bun run build` green.'
echo 'WARN: Run tests in tests/test_api_spa_endpoints.py'

echo 'Requirement 8: No mock/placeholder — every toggle maps to real pipeline behavior.'
python -m pytest

echo 'All verifications passed.'
